feat: Added internal ingress
wandb/helm-charts pull request #102
Opened 2024-03-29 07:32 UTC by amanpruthi

2024-03-29 13:50 UTC, wandb-zacharyblasczyk reviewed
@gls4 @nfoucha @jsbroks @adityachoudhari26

2024-03-29 13:50 UTC, wandb-zacharyblasczyk commented on charts/operator-wandb/Chart.yaml
> +version: 0.13.5
0.12.0?

2024-03-29 13:50 UTC, wandb-zacharyblasczyk commented on charts/operator-wandb/values.yaml
> +ingress_internal:
We don't use `_` I think camelCase is that is being standardized on. 

Also, what is the ing

2024-03-29 13:50 UTC, wandb-zacharyblasczyk commented on charts/operator-wandb/values.yaml
> +ingress_internal:
Also, if this is for privatLink, maybe we should call this 
```
privatLinkIngress:
  create: false
...
```

or 
```
offlineIngress:
  create: false
...
```

We should probably document that this ingress is only needed for GCP/Azure/Bare metal?

2024-04-30 15:50 UTC, jsbroks commented on charts/operator-wandb/templates/ingress.yaml
> +{{- if .Values.gcpPrivatLinkIngress.create }}
```suggestion
{{- if .Values.ingress.secondary.create }}
```

Lets generalize and call it `secondary`

2024-04-30 15:51 UTC, jsbroks requested changes

2024-04-30 15:51 UTC, jsbroks commented on charts/operator-wandb/templates/ingress.yaml
> +              number: 8082
Could we move this to a tpl and import that here? This way we only need to modify it in one place

2024-05-09 14:14 UTC, jsbroks commented on charts/operator-wandb/values.yaml
> +    create: true
```suggestion
    create: false
```

2024-05-09 14:16 UTC, jsbroks approved these changes

2024-05-10 15:56 UTC, jsbroks approved these changes

2024-05-17 12:22 UTC, merged

2024-06-20 16:22 UTC, zacharyblasczyk reviewed
Looks like a bit of copy paste.

2024-06-20 16:22 UTC, zacharyblasczyk commented on charts/operator-wandb/templates/ingress.yaml
> +    "kubernetes.io/ingress.allow-http" : "false"
Typo?

2024-06-20 16:22 UTC, zacharyblasczyk commented on charts/operator-wandb/values.yaml
> +    install: true
Unused?

2024-06-20 16:22 UTC, zacharyblasczyk commented on charts/operator-wandb/values.yaml
> +      email: support@wandb.com
Do these need to be wired up?