feat(backend): enable subpath for gcp
wandb/helm-charts pull request #173
Opened 2024-07-11 23:35 UTC by levinandrew

2024-07-11 23:42 UTC, vanpelt approved these changes

2024-07-11 23:49 UTC, jsbroks requested changes
You cannot change this, as it will break all azure instances

2024-07-11 23:49 UTC, jsbroks commented
You have to keep the name as path

2024-07-12 00:16 UTC, levinandrew commented
> You have to keep the name as path

@jsbroks instead of renaming `path`, what about just adding `subpath` as a new field? 

then in tf azure we could do https://github.com/wandb/terraform-azurerm-wandb/compare/levinandrew/byob-subpath?expand=1
<img width="305" alt="image" src="https://github.com/user-attachments/assets/294479fd-3895-4fa3-bc22-2128256e7191">

and in gcp/aws tf (where we don't use the `path` field yet) we could do https://github.com/wandb/terraform-google-wandb/pull/145/files
<img width="193" alt="image" src="https://github.com/user-attachments/assets/3cdaf877-42a6-4819-8b49-6ec8baf15ce8">

2024-07-12 02:03 UTC, jsbroks commented
I think we should leave it as path, since that is how its already templated and generally in infra, path references to what we are internally calling a subpath

2024-07-17 19:17 UTC, zacharyblasczyk approved these changes

2024-07-18 15:23 UTC, jsbroks approved these changes

2024-07-18 20:58 UTC, merged