chore: add nodeSelector, tolerations and affinity on controller
wandb/helm-charts pull request #237
Opened 2024-10-09 05:33 UTC by velotioaastha

2024-10-10 14:18 UTC, danielpanzella requested changes

2024-10-10 14:18 UTC, danielpanzella commented on charts/operator/templates/deployment.yaml
> +      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
can we change this match the formatting of others
```
nodeSelector:
  {{- .Values.nodeSelector | toYaml | nindent 8 }}
```

2024-10-17 17:07 UTC, zacharyblasczyk approved these changes

2024-11-07 07:00 UTC, velotioaastha commented
hey @danielpanzella can you approve this PR.

2024-11-07 15:13 UTC, merged