feat: Support secret keys configurable
wandb/helm-charts pull request #257
Opened 2024-11-06 06:55 UTC by amanpruthi

2024-11-06 10:48 UTC, flamarion reviewed
I think would be good to default all secrets to the previous key, like you did for Redis https://github.com/wandb/helm-charts/pull/257/files#diff-2820a1c4d6acfec8bdf8acd70e1a305cb1f536ae092834bd566632bcd86bbafdR134 
Another aspect I believe is necessary, is to make this optional.
The reason is because if some customer is already using this config and the operator pull the latest version of chart, this may break because the secret key will be required.

2024-11-06 18:07 UTC, danielpanzella requested changes
As pointed out by @flamarion [here](https://github.com/wandb/helm-charts/pull/257#pullrequestreview-2417935414) we need the values for the key to default to the previous value.

2024-11-07 06:58 UTC, velotioaastha commented
> Another aspect I believe is necessary, is to make this optional.
> The reason is because if some customer is already using this config and the operator pull the latest version of chart, this may break because the secret key will be required.

hey @danielpanzella @flamarion , we've added this already, you can check this here - 

For bucket - 
https://github.com/wandb/helm-charts/pull/257/files#diff-46611996f4a6fc6e0ffb1724cbd796c7fd5e7008c5c956ec1c071b38abf58d7bR21

For mysql - 
https://github.com/wandb/helm-charts/pull/257/files#diff-ce26fb708141f65196c806cca1ffc3d75fc1cda8c0a7ff615d6a097ae24abcb1R19
https://github.com/wandb/helm-charts/pull/257/files#diff-ce26fb708141f65196c806cca1ffc3d75fc1cda8c0a7ff615d6a097ae24abcb1R30

For redis - 
https://github.com/wandb/helm-charts/pull/257/files#diff-2820a1c4d6acfec8bdf8acd70e1a305cb1f536ae092834bd566632bcd86bbafdR134

2024-11-13 16:39 UTC, danielpanzella approved these changes

2024-11-14 04:55 UTC, merged