wandb chart config map
wandb/helm-charts pull request #83
Opened 2024-02-23 23:31 UTC by adityachoudhari26

2024-02-24 03:58 UTC, jsbroks commented on charts/operator/values.yaml
> +localRelease: false
I don't think we need this variable

2024-02-24 04:01 UTC, jsbroks commented on charts/operator/templates/configmap.yaml
> +    {{ .Values.wandbChartBinary }}
```suggestion
  wandb-chart.tgz: {{ .Files.Get (.Value.chartPath) | b64enc }}
```

Maybe we could do something like that?

2024-02-27 20:45 UTC, jsbroks commented on charts/operator/values.yaml
> +chartPath: ""
```suggestion
charts:
   MY_CHART: './path/tar.gz'
```

2024-02-27 20:46 UTC, jsbroks commented on charts/operator/templates/configmap.yaml
> +  name: wandb-chart-configmap
You need to prefix stuff with chart name or you can get conficts

2024-02-27 20:48 UTC, jsbroks commented on charts/operator/templates/deployment.yaml
> +          value: {{ .Values.localRelease | quote }}
```suggestion
        - name: IS_AIRGAPPED
          value: {{ .Values.airgapped | quote }}
```

2024-02-27 23:59 UTC, adityachoudhari26 commented on charts/operator/templates/configmap.yaml
> +    {{ .name }}.b64: {{ $.Files.Get .path | b64enc }}
we are explicitly annotating with `.b64` - in operator code, we check if the file has this extension and handle accordingly

2024-02-28 02:45 UTC, jsbroks commented on charts/operator/templates/deployment.yaml
> +        - name: AIRGAPPED
```suggestion
        - name: `IS_AIRGAPPED`
```

2024-02-28 02:46 UTC, jsbroks requested changes

2024-02-28 02:46 UTC, jsbroks commented on charts/operator/templates/deployment.yaml
> +        - name: {{ include "name" . }}-chart-configmap
```suggestion
        - name: {{ include "name" . }}-charts
```

2024-02-28 02:46 UTC, jsbroks commented on charts/operator/templates/deployment.yaml
> +          name: {{ include "name" . }}-chart-configmap
```suggestion
      - name: {{ include "name" . }}-charts
        configMap:
          name: {{ include "name" . }}-charts
```

2024-02-28 02:46 UTC, jsbroks commented on charts/operator/values.yaml
> +charts: []
List can we do key string? and iterate object?
```suggestion
charts: {}
```

2024-02-29 00:50 UTC, jsbroks commented on charts/operator/templates/configmap.yaml
> +  name: {{ include "name" . }}-chart-configmap
```suggestion
  name: {{ include "name" . }}-charts
```

2024-02-29 00:50 UTC, jsbroks commented on charts/operator/templates/deployment.yaml
> +          value: {{ .Values.airgapped | quote }}
bra -.-

2024-02-29 00:51 UTC, jsbroks approved these changes

2024-02-29 04:05 UTC, merged